language: node_js
node_js:
  - "6.1"

services:
  - redis-server

before_script:
  - echo current directory $TRAVIS_BUILD_DIR
  - npm install serverless -g
  - mkdir lexofood_db
  - sls dynamodb start -d $TRAVIS_BUILD_DIR/lexofood_db/ -m
  - sleep 5

script:
  - "npm test;"
  - "cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

env:
  matrix:
    - COVERAGE=1

sudo: false
