language: node_js
node_js:
  - "6.1"

services:
  - redis-server

before_script:
  - echo current directory $(pwd)
  - sleep 1

script:
  - "npm test;"
  - "cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

env:
  matrix:
    - COVERAGE=1

sudo: false
