service: users
provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  memorySize: 512 # Overwrite the default memory size. Default is 1024
  versionFunctions: false # Optional function versioning
  stackTags: # Optional CF stack tags
    name: lexofood-${self:provider.stage}
custom:
  defaultStage: dev
  profiles:
    dev: lexofood-dev
    prod: lexofood-prod
functions:
  usersCreate:
    handler: users/handler
    events:
      - http: post users
  usersGet:
    handler: users/handler.getUser
    events:
      - http: get users
  usersUpdate:
    handler: users/handler
    events:
      - http: put users
  usersDelete:
    handler: users/handler
    events:
      - http: delete users
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: uid
            AttributeType: B
          #- AttributeName: firstName
          #  AttributeType: S
          #- AttributeName: lastName
          #  AttributeType: S
          #- AttributeName: sex
          #  AttributeType: S
          #- AttributeName: email
          #  AttributeType: S
          #- AttributeName: mobile
          #  AttributeType: S
          #- AttributeName: createdAt
          #  AttributeType: S
          #- AttributeName: updatedAt
          #  AttributeType: S
        KeySchema:
          - AttributeName: uid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    